title: Halo PE (HPEM4Win)
description: Halo Portable Edition Maker for Windows
theme: jekyll-theme-slate
github:
  exe_url: https://github.com/SparrOSDeveloperTeam/halo/releases/v1.0/halopem_setup_1.0.exe
  zip_url: https://github.com/SparrOSDeveloperTeam/halo/releases/v1.0/halopem_1.0_files.zip
